openai_sdk_llms:
  Qwen/Qwen2.5-72B-Instruct: DEEPINFRA
  deepseek-chat: DEEPSEEK
  glm-4: ZHIPU
  glm-4-plus: ZHIPU
  glm-4v: ZHIPU
  glm-4v-plus: ZHIPU
  google/gemma-2-27b-it: DEEPINFRA
  gpt-3.5-turbo: OPENAI
  gpt-4o: OPENAI
  gpt-4o-mini: OPENAI
  internLM-72B: INTERN
  meta-llama/Llama-2-13b-chat-hf: DEEPINFRA
  meta-llama/Llama-3.2-11B-Vision-Instruct: DEEPINFRA
  meta-llama/Llama-3.2-90B-Vision-Instruct: DEEPINFRA
  meta-llama/Meta-Llama-3-70B-Instruct: DEEPINFRA
  meta-llama/Meta-Llama-3-8B-Instruct: DEEPINFRA
  meta-llama/Meta-Llama-3.1-70B-Instruct: DEEPINFRA
  meta-llama/Meta-Llama-3.1-8B-Instruct: DEEPINFRA
  mistralai/Mistral-7B-Instruct-v0.3: DEEPINFRA
  mistralai/Mixtral-8x22B-Instruct-v0.1: DEEPINFRA
  mistralai/Mixtral-8x7B-Instruct-v0.1: DEEPINFRA
  mistralai/Mixtral-8x7B-Instruct-v0.1: DEEPINFRA
  Qwen/QwQ-32B-Preview: DEEPINFRA
  qwen/qwen-2-vl-72b-instruct: OPENROUTER
  text-embedding-ada-002: OPENAI
  yi-lightning: YI
openai_sdk_vlms:
  glm-4v: ZHIPU
  glm-4v-plus: ZHIPU
  gpt-4o: OPENAI
  gpt-4o-mini: OPENAI
  internLM-72B: INTERN
  meta-llama/Llama-3.2-11B-Vision-Instruct: DEEPINFRA
  meta-llama/Llama-3.2-90B-Vision-Instruct: DEEPINFRA
  qwen-vl-max-0809: QWEN
  qwen/qwen-2-vl-72b-instruct: OPENROUTER
other_sdk_llms:
  claude-3-5-sonnet-20240620: ANTHROPIC
  claude-3-haiku-20240307: ANTHROPIC
  claude-3-opus-20240229: null
  command-r-08-2024: COHERE
  command-r-plus-08-2024: COHERE
  gemini-1.5-flash: GOOGLE
  gemini-1.5-pro: GOOGLE
other_sdk_vlms:
  claude-3-5-sonnet-20240620: ANTHROPIC
  claude-3-haiku-20240307: ANTHROPIC
  gemini-1.5-flash: GOOGLE
  gemini-1.5-pro: GOOGLE
t2i_models:
  HunyuanDiT: LOCAL
  cogView-3-plus: ZHIPU
  dall-e-3: OPENAI
  flux-1.1-pro: REPLICATE
  flux_schnell: REPLICATE
  kolors: LOCAL
  playground-v2.5: LOCAL
  playgroundai/playground-v2.5-1024px-aesthetic: REPLICATE
  sd-3.5-large: LOCAL
  sd-3.5-large-turbo: LOCAL
