MODEL_NAME_MAPPINGS:
  HunyuanDiT: HunyuanDiT
  claude-3-haiku: claude-3-haiku-20240307
  claude-3-opus: claude-3-opus-20240229
  claude-3.5-haiku: later
  claude-3.5-opus: later
  claude-3.5-sonnet: claude-3-5-sonnet-20240620
  cogview-3-plus: cogView-3-plus
  command-r: command-r-08-2024
  command-r-plus: command-r-plus-08-2024
  dalle3: dall-e-3
  deepseek-chat: deepseek-chat
  flux-1.1-pro: flux-1.1-pro
  gemini-1.5-flash: gemini-1.5-flash
  gemini-1.5-pro: gemini-1.5-pro
  gemma-2-27B: google/gemma-2-27b-it
  glm-4: glm-4
  glm-4-plus: glm-4-plus
  glm-4v: glm-4v
  glm-4v-plus: glm-4v-plus
  gpt-3.5-turbo: gpt-3.5-turbo
  gpt-4o: gpt-4o
  gpt-4o-mini: gpt-4o-mini
  internLM-72B: internLM-72B
  kolors: kolors
  llama-2-13B: meta-llama/Llama-2-13b-chat-hf
  llama-3-70B: meta-llama/Meta-Llama-3-70B-Instruct
  llama-3-8B: meta-llama/Meta-Llama-3-8B-Instruct
  llama-3.1-70B: meta-llama/Meta-Llama-3.1-70B-Instruct
  llama-3.1-8B: meta-llama/Meta-Llama-3.1-8B-Instruct
  llama-3.2-11B-V: meta-llama/Llama-3.2-11B-Vision-Instruct
  llama-3.2-90B-V: meta-llama/Llama-3.2-90B-Vision-Instruct
  mistral-7B: mistralai/Mistral-7B-Instruct-v0.3
  mistral-8x22B: mistralai/Mixtral-8x22B-Instruct-v0.1
  mistral-8x7B: mistralai/Mixtral-8x7B-Instruct-v0.1
  o1: o1
  o1-mini: o1-mini
  o1-preview: o1-preview
  playground-v2.5: playground-v2.5
  qwen-2-vl-72B: qwen-vl-max-0809
  qwen-2.5-72B: Qwen/Qwen2.5-72B-Instruct
  qwen-vl-max-0809: qwen-vl-max-0809
  qwq-32B: Qwen/QwQ-32B-Preview
  sd-3.5-large: sd-3.5-large
  sd-3.5-large-turbo: sd-3.5-large-turbo
  text-embedding-ada-002: text-embedding-ada-002
  yi-lightning: yi-lightning

local_openai_sdk_llms:
  meta-llama/Llama-2-13b-chat-hf: LOCAL
openai_sdk_llms:
  Qwen/QwQ-32B-Preview: DEEPINFRA
  Qwen/Qwen2.5-72B-Instruct: DEEPINFRA
  deepseek-chat: DEEPSEEK
  glm-4: ZHIPU
  glm-4-plus: ZHIPU
  glm-4v: ZHIPU
  glm-4v-plus: ZHIPU
  google/gemma-2-27b-it: DEEPINFRA
  gpt-3.5-turbo: OPENAI
  gpt-4o: OPENAI
  gpt-4o-mini: OPENAI
  internLM-72B: INTERN
  meta-llama/Llama-2-13b-chat-hf: DEEPINFRA
  meta-llama/Llama-3.2-11B-Vision-Instruct: DEEPINFRA
  meta-llama/Llama-3.2-90B-Vision-Instruct: DEEPINFRA
  meta-llama/Meta-Llama-3-70B-Instruct: DEEPINFRA
  meta-llama/Meta-Llama-3-8B-Instruct: DEEPINFRA
  meta-llama/Meta-Llama-3.1-70B-Instruct: DEEPINFRA
  meta-llama/Meta-Llama-3.1-8B-Instruct: DEEPINFRA
  mistralai/Mistral-7B-Instruct-v0.3: DEEPINFRA
  mistralai/Mixtral-8x22B-Instruct-v0.1: DEEPINFRA
  mistralai/Mixtral-8x7B-Instruct-v0.1: DEEPINFRA
  o1: OPENAI
  o1-mini: OPENAI
  o1-preview: OPENAI
  qwen-vl-max-0809: QWEN
  qwen/qwen-2-vl-72b-instruct: OPENROUTER
  text-embedding-ada-002: OPENAI
  yi-lightning: YI
openai_sdk_vlms:
  glm-4v: ZHIPU
  glm-4v-plus: ZHIPU
  gpt-4o: OPENAI
  gpt-4o-mini: OPENAI
  internLM-72B: INTERN
  meta-llama/Llama-3.2-11B-Vision-Instruct: DEEPINFRA
  meta-llama/Llama-3.2-90B-Vision-Instruct: DEEPINFRA
  qwen-vl-max-0809: QWEN
  qwen/qwen-2-vl-72b-instruct: OPENROUTER
other_sdk_llms:
  claude-3-5-sonnet-20240620: ANTHROPIC
  claude-3-haiku-20240307: ANTHROPIC
  claude-3-opus-20240229: null
  command-r-08-2024: COHERE
  command-r-plus-08-2024: COHERE
  gemini-1.5-flash: GOOGLE
  gemini-1.5-pro: GOOGLE
other_sdk_vlms:
  claude-3-5-sonnet-20240620: ANTHROPIC
  claude-3-haiku-20240307: ANTHROPIC
  gemini-1.5-flash: GOOGLE
  gemini-1.5-pro: GOOGLE
t2i_models:
  HunyuanDiT: LOCAL
  cogView-3-plus: ZHIPU
  dall-e-3: OPENAI
  flux-1.1-pro: REPLICATE
  flux_schnell: REPLICATE
  kolors: LOCAL
  playground-v2.5: LOCAL
  playgroundai/playground-v2.5-1024px-aesthetic: REPLICATE
  sd-3.5-large: LOCAL
  sd-3.5-large-turbo: LOCAL
